# Generated by Django 5.0.2 on 2024-03-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='_image',
        ),
    ]
