# Generated by Django 5.0.2 on 2024-08-05 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0006_alter_completedtask_level_alter_completedtask_task_and_more'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='_file',
            field=models.FileField(upload_to='materialsFiles/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='material',
            name='level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='level.level', verbose_name='уровень'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='site',
            name='href',
            field=models.URLField(verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='site',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='material.material', verbose_name='материал'),
        ),
    ]
