# Generated by Django 5.0.2 on 2024-03-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_material_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(default='', upload_to='materialsFiles/'),
            preserve_default=False,
        ),
    ]
