# Generated by Django 5.0.2 on 2024-03-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_material_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='file',
            new_name='_file',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='image',
            new_name='_image',
        ),
    ]
