# Generated by Django 5.0.2 on 2024-03-12 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('_image', models.ImageField(upload_to='levelsImage/')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='language.language')),
                ('users', models.ManyToManyField(db_table='CompletedLevel', related_name='completed_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'db_table': 'Level',
                'unique_together': {('language', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completedTasks', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completedTasks', to='level.level')),
            ],
            options={
                'verbose_name': 'Законченное задание',
                'verbose_name_plural': 'Законченные задания',
                'db_table': 'CompletedTask',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='level.level')),
                ('users', models.ManyToManyField(related_name='completed_tasks', through='level.CompletedTask', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'Task',
                'unique_together': {('number', 'level')},
            },
        ),
        migrations.AddField(
            model_name='completedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completedTasks', to='level.task'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('text', models.CharField(max_length=300)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='level.task')),
            ],
            options={
                'verbose_name': 'Тест кейс',
                'verbose_name_plural': 'Тест кейсы',
                'db_table': 'TestCase',
            },
        ),
    ]
