# Generated by Django 5.0.2 on 2024-03-11 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('level', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='users',
            field=models.ManyToManyField(db_table='CompletedLevel', related_name='completed_levels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='level.level'),
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(db_table='CompletedTask', related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testcase',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='level.task'),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('language', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('number', 'level')},
        ),
    ]
