# Generated by Django 5.0.2 on 2024-03-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
