# Generated by Django 5.0.2 on 2024-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_alter_level_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
