# Generated by Django 5.0.2 on 2024-03-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_alter_level_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('number', 'level')},
        ),
    ]
