# Generated by Django 5.0.2 on 2024-03-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_task_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['number'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
