# Generated by Django 5.0.2 on 2024-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_alter_task_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='levelsImage/'),
        ),
    ]
