# Generated by Django 5.0.2 on 2024-08-05 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0006_alter_language__image_alter_language_accepted_users_and_more'),
        ('level', '0005_alter_level_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtask',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completedTasks', to='level.level', verbose_name='урвоень'),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completedTasks', to='level.task', verbose_name='задача'),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completedTasks', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='level',
            name='_image',
            field=models.ImageField(upload_to='levelsImage/', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='level',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='language.language', verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='level',
            name='number',
            field=models.PositiveIntegerField(verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='level',
            name='users',
            field=models.ManyToManyField(db_table='CompletedLevel', related_name='completedLevels', to=settings.AUTH_USER_MODEL, verbose_name='сдавшие'),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='level.level', verbose_name='уровень'),
        ),
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.PositiveIntegerField(verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.PositiveIntegerField(verbose_name='время (минуты)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(related_name='completed_tasks', through='level.CompletedTask', to=settings.AUTH_USER_MODEL, verbose_name='сдавшие'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='code',
            field=models.TextField(verbose_name='код проверки'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testCases', to='level.task', verbose_name='задача'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='text',
            field=models.CharField(max_length=300, verbose_name='текст'),
        ),
    ]
