# Generated by Django 5.0.2 on 2024-08-07 11:00

import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='возрас')),
                ('group', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='группа')),
                ('_photo', models.ImageField(blank=True, null=True, upload_to='usersPhotos/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'User',
            },
            managers=[
                ('objects', users.managers.CustomUserManager()),
            ],
        ),
    ]
