# Generated by Django 5.0.2 on 2024-03-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_photo_user__photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
