# Generated by Django 5.0.2 on 2024-03-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='_photo',
        ),
    ]
