# Generated by Django 5.0.2 on 2024-03-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_photo_user__photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_photo',
            new_name='photo',
        ),
    ]
