# Generated by Django 5.0.2 on 2024-08-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QestionImage',
            new_name='QuestionImage',
        ),
        migrations.AlterModelTable(
            name='questionimage',
            table='QuestionImage',
        ),
    ]
