# Generated by Django 5.0.2 on 2024-08-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_rename_qestionimage_questionimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='percentage_difference',
        ),
    ]
