# Generated by Django 5.0.2 on 2024-08-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_test_percentage_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='mark',
            field=models.FloatField(),
        ),
    ]
