# Generated by Django 5.0.2 on 2024-08-07 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('js', 'JavaScript'), ('py', 'Python')], max_length=150, unique=True, verbose_name='название')),
                ('_image', models.ImageField(upload_to='languagesIcons/', verbose_name='картинка')),
                ('is_closed', models.BooleanField(default=False, verbose_name='является ли закрытым')),
                ('accepted_users', models.ManyToManyField(db_table='Accepted_Users', related_name='acceptedLanguages', to=settings.AUTH_USER_MODEL, verbose_name='допущенные пользователи')),
                ('users', models.ManyToManyField(db_table='CompletedLanguage', related_name='completedLanguages', to=settings.AUTH_USER_MODEL, verbose_name='сдавшие')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'db_table': 'Language',
            },
        ),
    ]
