# Generated by Django 5.0.2 on 2024-03-11 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='users',
            field=models.ManyToManyField(db_table='CompletedLanguage', related_name='completed_languages', to=settings.AUTH_USER_MODEL),
        ),
    ]
