# Generated by Django 5.0.2 on 2024-08-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('js', 'JavaScript'), ('py', 'Python')], max_length=150, verbose_name='название'),
        ),
    ]
