# Generated by Django 5.0.2 on 2024-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_alter_language_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('js', 'JavaScript')], max_length=150, unique=True),
        ),
    ]
