# Generated by Django 5.0.2 on 2024-03-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_alter_language_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='icon',
        ),
        migrations.AddField(
            model_name='language',
            name='_icon',
            field=models.ImageField(default='', upload_to='languagesIcons/'),
            preserve_default=False,
        ),
    ]
