# Generated by Django 5.0.2 on 2024-03-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_remove_language_icon_language__icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='_icon',
            new_name='_image',
        ),
    ]
