# Generated by Django 5.0.2 on 2024-03-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('js', 'JavaScript'), ('py', 'Python')], max_length=150, unique=True),
        ),
    ]
